import { Helmet } from "react-helmet";

export default function PrivacyPolicy() {
    return (
        <div id="privacy-policy">
            <Helmet>
                <link rel="canonical" href="https://higherorlower.co.uk/privacy-policy" />
                <title>Privacy Policy • Higher or Lower</title>
                <meta name="description" content="The privacy policy for HigherorLower.co.uk." />
            </Helmet>

            <header className="max-width">
                <h1>Privacy Policy</h1>
            </header>

            <main className="max-width">
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

                <h2>Interpretation and Definitions</h2>

                <h3>Interpretation</h3>

                <p>The words of which the initial letter is capitalised have meanings defined under the following conditions.</p>
                <p>The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                <h3>Definitions</h3>

                <p>For the purposes of this Privacy Policy:</p>

                <ul>
                    <li><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.</li>
                    <li><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HigherorLower.co.uk. For the purpose of the GDPR, the Company is the Data Controller.</li>
                    <li><b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><b>Website</b> refers to HigherorLower.co.uk, accessible from https://higherorlower.co.uk/</li>
                    <li><b>Service</b> refers to the Website.</li>
                    <li><b>Country</b> refers to: United Kingdom</li>
                    <li><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.</li>
                    {/* <li><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User can log in or create an account to use the Service. Facebook Fan Page is a public profile named HigherorLower.co.uk specifically created by the Company on the Facebook social network, accessible from https://www.facebook.com/higherorlower.co.uk</li> */}
                    <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual. For the purposes for GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity.</li>
                    <li><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><b>Device</b> means any device that can access the Service such as a computer, a mobile phone or a digital tablet.</li>
                    <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><b>Data Controller</b>, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
                </ul>


                <h2>Collecting and Using Your Personal Data</h2>

                <h3>Types of Data Collected</h3>

                <h4>Personal Data</h4>

                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Address, County, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>

                <h4>Usage Data</h4>

                <p>Usage Data is collected automatically when using the Service.</p>

                <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

                <h4>Tracking Technologies and Cookies</h4>

                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies we may use include beacons, tags, and scripts to collect and track information and to improve and analyse Our Service.</p>
                <p>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
                <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies in the "<a href="https://www.privacypolicies.com/blog/eu-cookies-directive/" target="_blank" rel="noreferrer">What Are Cookies</a>" article.</p>

                <h5>Necessary / Essential Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Third-Parties</p>
                <p><b>Purpose</b>: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features or new functionality of the Website to see how our users react to them.</p>

                <h5>Cookies Policy / Notice Acceptance Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Us</p>
                <p><b>Purpose</b>: These Cookies identify if users have accepted the use of cookies on the Website.</p>

                <h5>Functionality Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Us</p>
                <p><b>Purpose</b>: These Cookies allow us to remember choices You make when You use the Website, such as language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>

                <h5>Tracking and Performance Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Third-Parties</p>
                <p><b>Purpose</b>: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features or new functionality of the Website to see how our users react to them.</p>

                <h5>Targeting and Advertising Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Third-Parties</p>
                <p><b>Purpose</b>: These Cookies track your browsing habits to enable Us to show advertising which is more likely to be of interest to You. These Cookies use information about your browsing history to group You with other users who have similar interests. Based on that information, and with Our permission, third party advertisers can place Cookies to enable them to show adverts which We think will be relevant to your interests while You are on third party websites.</p>

                <h5>Social Media Cookies</h5>

                <p><b>Type</b>: Persistent Cookies</p>
                <p><b>Administered by</b>: Third-Parties</p>
                <p><b>Purpose</b>: In addition to Our own Cookies, We may also use various third parties Cookies to report usage statistics of the Website, deliver advertisements on and through the Website, and so on. These Cookies may be used when You share information using a social media networking websites such as Facebook, Instagram or Twitter.</p>

                <h3>Use of Your Personal Data</h3>   

                <p>The Company may use Personal Data for the following purposes:</p>

                <ul>
                    <li><b>To provide and maintain our Service</b>, including to monitor the usage of our Service.</li>
                    <li><b>For the performance of a contract</b>: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li><b>To contact You</b>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    <li><b>To provide You with news, special offers and general information about other goods, services and events</b> which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                    <li><b>To manage Your requests</b>: To attend and manage Your requests to Us.</li>
                </ul>

                <p>We may share your personal information in the following situations:</p>

                <ul>
                    <li><b>With Service Providers</b>: We may share Your personal information with Service Providers to monitor and analyse the use of our Service, to show advertisements to You to help support and maintain Our Service, to advertise on third party websites to You after You visited our Service, to contact You.</li>
                    <li><b>For Business transfers</b>: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
                    <li><b>With Affiliates</b>: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                    <li><b>With Business partners</b>: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                    <li><b>With other users</b>: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
                </ul>

                <h3>Retention of Your Personal Data</h3>

                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

                <h3>Transfer of Your Personal Data</h3>

                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your county, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

                <h3>Disclosure of Your Personal Data</h3>

                <h4>Business Transactions</h4>

                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                <h4>Law enforcement</h4>

                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

                <h4>Other legal requirements</h4>

                <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

                <ul>
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </ul>

                <h3>Security of Your Personal Data</h3>

                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

                <h3>Detailed Information on the Processing of Your Personal Data</h3>

                <p>Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.</p>

                <h4>Analytics</h4>

                <p>We may use third-party Service providers to monitor and analyse the use of our Service.</p>

                <h5>Google Analytics</h5>

                <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
                <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
                <p>For more information on the privacy practices of Google, please visit the <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noreferrer">Google Privacy & Terms web page</a>.</p>

                <h4>Advertising</h4>

                <p>We may use Service providers to show advertisements to You to help support and maintain Our Service.</p>

                <h5>Google AdSense & DoubleClick Cookie</h5>

                <p>Google, as a third-party vendor, uses cookies to serve ads on our Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet.</p>
                <p>You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the <a href="http://www.google.com/ads/preferences/" target="_blank" rel="noreferrer">Google Ads Settings web page</a>.</p>

                <h5>Bing Ads</h5>

                <p>Bing Ads is an advertising service provided by Microsoft Inc.</p>
                <p>You can opt-out from Bing Ads by following the instructions on <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads" target="_blank" rel="noreferrer">Bing Ads Opt-out page</a>.</p>
                <p>For more information about Bing Ads, please visit their <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" target="_blank" rel="noreferrer">Privacy Policy</a>.</p>

                <h4>Email Marketing</h4>

                <p>We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
                <p>We may use Email Marketing Service Providers to manage and send emails to You.</p>

                <h4>Behavioural Remarketing</h4>

                <p>The Company may use remarketing services to advertise on third party websites to You after You visited our Service. We and Our third-party vendors may use cookies to inform, optimise and serve ads based on Your past visits to our Service.</p>

                <h5>Google Ads (AdWords)</h5>

                <p>Google Ads (AdWords) remarketing service is provided by Google Inc.</p>
                <p>You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the <a href="http://www.google.com/settings/ads" target="_blank" rel="noreferrer">Google Ads Settings page</a>.</p>
                <p>Google also recommends installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noreferrer">Google Analytics Opt-out Browser Add-on</a> for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</p>
                <p>For more information on the privacy practices of Google, please visit the <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noreferrer">Google Privacy & Terms web page</a>.</p>

                <h5>Bing Ads Remarketing</h5>

                <p>Bing Ads remarketing service is provided by Microsoft Inc.</p>
                <p>You can opt-out of Bing Ads interest-based ads by following their <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads" target="_blank" rel="noreferrer">instructions</a>.</p>
                <p>You can learn more about the privacy practices and policies of Microsoft by visiting their <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" target="_blank" rel="noreferrer">Privacy Policy page</a>.</p>

                <h5>Twitter</h5>

                <p>Twitter remarketing service is provided by Twitter Inc.</p>
                <p>You can opt-out from Twitter's interest-based ads by following their <a href="https://support.twitter.com/articles/20170405" target="_blank" rel="noreferrer">instructions</a>.</p>
                <p>You can learn more about the privacy practices and policies of Twitter by visiting their <a href="https://twitter.com/privacy" target="_blank" rel="noreferrer">Privacy Policy page</a>.</p>

                <h5>Facebook</h5>

                <p>Facebook remarketing service is provided by Facebook Inc.</p>
                <p>To opt-out from Facebook's interest-based ads, follow these instructions from <a href="https://www.facebook.com/help/568137493302217" target="_blank" rel="noreferrer">Facebook</a>.</p>
                <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the <a href="http://www.aboutads.info/choices/" target="_blank" rel="noreferrer">Digital Advertising Alliance in the USA</a>, the <a href="http://youradchoices.ca/" target="_blank" rel="noreferrer">Digital Advertising Alliance of Canada in Canada</a> or the <a href="http://www.youronlinechoices.eu/" target="_blank" rel="noreferrer">European Interactive Digital Advertising Alliance in Europe</a>, or opt-out using your mobile device settings.</p>
                <p>For more information on the privacy practices of Facebook, please visit <a href="https://www.facebook.com/privacy/explanation" target="_blank" rel="noreferrer">Facebook's Data Policy</a>.</p>

                <h5>Pinterest</h5>

                <p>Pinterest remarketing service is provided by Pinterest Inc.</p>
                <p>You can opt-out from Pinterest's interest-based ads by enabling the "Do Not Track" functionality of your web browser or by following <a href="http://help.pinterest.com/en/articles/personalization-and-data" target="_blank" rel="noreferrer">Pinterest instructions</a>.</p>
                <p>You can learn more about the privacy practices and policies of Pinterest by visiting their <a href="https://about.pinterest.com/en/privacy-policy" target="_blank" rel="noreferrer">Privacy Policy page</a>.</p>

                <h2>GDPR Privacy</h2>

                <h3>Legal Basis for Processing Personal Data under GDPR</h3>

                <p>We may process Personal Data under the following conditions:</p>

                <ul>
                    <li><b>Consent</b>: You have given Your consent for processing Personal Data for one or more specific purposes.</li>
                    <li><b>Performance of a contract</b>: Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
                    <li><b>Legal obligations</b>: Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
                    <li><b>Vital interests</b>: Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
                    <li><b>Public interests</b>: Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
                    <li><b>Legitimate interests</b>: Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
                </ul>

                <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>

                <h3>Your Rights under the GDPR</h3>

                <p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.</p>
                <p>You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>

                <ul>
                    <li><b>Request access to Your Personal Data</b>. The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.</li>
                    <li><b>Request correction of the Personal Data that We hold about You</b>. You have the right to have any incomplete or inaccurate information We hold about You corrected.</li>
                    <li><b>Object to processing of Your Personal Data</b>. This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</li>
                    <li><b>Request erasure of Your Personal Data</b>. You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
                    <li><b>Request the transfer of Your Personal Data</b>. We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</li>
                    <li><b>Withdraw Your consent</b>. You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</li>
                </ul>

                <h3>Exercising of Your GDPR Data Protection Rights</h3>

                <p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.</p>
                <p>You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>

                {/* <h2>Facebook Fan Page</h2>

                <h3>Data Controller for the Facebook Fan Page</h3>

                <p>The Company is the Data Controller of Your Personal Data collected while using the Service. As operator of the (<a href="https://www.facebook.com/higherorlower" target="_blank" rel="noreferrer">Facebook Fan Page</a>), the Company and the operator of the social network Facebook are Joint Controllers.</p>
                <p>The Company has entered into agreements with Facebook that define the terms for use of the Facebook Fan Page, among other things. These terms are mostly based on the <a href="https://www.facebook.com/terms.php" target="_blank" rel="noreferrer">Facebook Terms of Service</a>.</p>
                <p>Visit the <a href="https://www.facebook.com/policy.php" target="_blank" rel="noreferrer">Facebook Privacy Policy</a> for more information about how Facebook manages Personal data.</p>

                <h3>Facebook Insights</h3>

                <p>We use the Facebook Insights function in connection with the operation of the Facebook Fan Page and on the basis of the GDPR, in order to obtain anonymised statistical data about Our users.</p>
                <p>For this purpose, Facebook places a Cookie on the device of the user visiting Our Facebook Fan Page. Each Cookie contains a unique identifier code and remains active for a period of two years, except when it is deleted before the end of this period.</p>
                <p>Facebook receives, records and processes the information stored in the Cookie, especially when the user visits the Facebook services, services that are provided by other members of the Facebook Fan Page and services by other companies that use Facebook services.</p>
                <p>For more information on the privacy practices of Facebook, please visit their <a href="https://www.facebook.com/policy.php" target="_blank" rel="noreferrer">Facebook Privacy Policy page</a>.</p> */}

                <h2>Children's Privacy</h2>

                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>

                <h2>Links to Other Websites</h2>

                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>

                <h2>Changes to this Privacy Policy</h2>

                <p>We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                <h2>Contact Us</h2>

                <p>If you have any questions about this Privacy Policy, You can contact us by sending an email to hi@higherorlower.co.uk.</p>
            </main>
        </div>
    )
}